$latex = 'pdflatex';
$bibtex = 'bibtex';
$makeindex = 'mendex -U %O -o %D %S';
$pdf_mode = 3; 
$ENV{TZ} = 'Asia/Tokyo';
$ENV{OPENTYPEFONTS} = '/usr/share/fonts//:';
$ENV{TTFONTS} = '/usr/share/fonts//:';
$pdf_previewer = 'skim %S';
